New-CmAzCore Initial Deployment
Trustmarque/cloudmarque-azure-pwsh pull request #106
Opened 2020-10-15 16:41 UTC by deepend-dev

![image](https://user-images.githubusercontent.com/55054090/96160315-b0322580-0f0d-11eb-9ef5-c21444f08c86.png)

2020-10-15 17:01 UTC, tm-luke requested changes

2020-10-15 17:01 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/core.yml
> +service:
Something to think about, instead of the original suggestion of a parameter per resource settings file, we could add the paths to those settings files in the core settings file instead. This would reduce duplication of settings if we instead did the following in core.yml:

location:
name:
automationSettings <filepath>
budgetsettings: <filepath>
keyvaultSettings: <filepath>
monitorsettings: <filepath>

2020-10-16 08:19 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Core/New-CmAzCore.ps1
> +                    $TagSettingsFile = "$((Get-CmAzContext).projectRoot)/_tags/globalTags.yml"
its either this or I need to write deployment command twice with if else - one with tagsettings and one without

2020-10-16 08:21 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Core/New-CmAzCore.ps1
> +                $SettingsObject.budgets = @(@{
_was failing if I dont provide defaults :_

elseif (!($budget.startDate -Is [DateTime])) {
					Write-Error "Please ensure the budget start date is a valid date." -Category InvalidArgument -CategoryTargetName "Budgets.StartDate"
				}

2020-10-16 08:30 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Core/automation/New-CmAzCoreAutomation.ps1
> +				$nameResourceGroup = Get-CmAzResourceName -Resource "ResourceGroup" -Architecture "Core" -Region $location -Name "$item-$($SettingsObject.name)"
its same as monitoring.. we need two different resources groups and automation accounts depending on name context.. $item is used because of old style of foreach statement usage.. its an old command which needs further improvements in its own branch

2020-10-16 08:30 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Core/automation/New-CmAzCoreAutomation.ps1
> +				$automationAccountName = Get-CmAzResourceName -Resource "Automation" -Architecture "Core" -Region $location -Name "$item-$($SettingsObject.name)"
same a above

2020-10-16 08:31 UTC, tm-luke commented on Cloudmarque.Azure/Public/Core/New-CmAzCore.ps1
> +                $SettingsObject.budgets = @(@{
Yeah, you just need to provide a valid date in settings file.

2020-10-16 08:33 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/core.yml
> +service:
its debatable .. Since all the settings are optional. Additional settings are only required if you overwrite them.. infact it helps inter linking of core elements in much simpler way..

2020-10-16 12:45 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Core/New-CmAzCore.ps1
> +                $SettingsObject.budgets = @(@{
new implementation

2020-10-16 12:45 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Core/New-CmAzCore.ps1
> +            }
done

2020-10-16 14:29 UTC, tm-luke requested changes

2020-10-19 07:48 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Core/New-CmAzCore.ps1
> +        [Security.SecureString]$AutomationCertificatePassword
done

2020-10-19 07:52 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Core/New-CmAzCore.ps1
> +                    $SettingsObject.monitorSettings = "$Directory/monitor.yml"
done

2020-10-19 07:53 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Core/New-CmAzCore.ps1
> +
done

2020-10-19 08:54 UTC, merged