General - relative path handling
Trustmarque/cloudmarque-azure-pwsh pull request #167
Opened 2020-12-21 12:14 UTC by deepend-dev

resolves #160

2020-12-21 12:16 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +										$interimGroupPath = "$(Split-Path $interimPath)/groups/$_"
This path is not provided by user and is only internal to code..

2020-12-21 12:16 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +						$interimPath = Resolve-FilePath -NestedFile $ymlObject
resolves relative path provided by user with project root of cloudmarque context ..

2020-12-21 14:42 UTC, tm-luke requested changes

2020-12-21 14:42 UTC, tm-luke commented on Cloudmarque.Azure/Public/Core/New-CmAzCore.ps1
> +                $SettingsObject.($SettingsFile.Replace('Settings', '')) = Get-CmAzSettingsFile -Path $SettingsObject.$SettingsFile
This is unneeded, either set the properties in the settingsfile or leave them as is.

2020-12-21 14:42 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +						$interimPath = Resolve-FilePath -NestedFile $ymlObject
Do we want to handle full directory paths?

2020-12-21 14:42 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +						$interimPath = Resolve-FilePath -NestedFile $ymlObject
This also kinda duplicates the checks in resolve-filepath

2020-12-21 14:42 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +						write-verbose "Importing virtual networks ..."
Write-Verbose, can you do the same changes to below as well

2020-12-23 14:27 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Core/New-CmAzCore.ps1
> +                $SettingsObject.($SettingsFile.Replace('Settings', '')) = Get-CmAzSettingsFile -Path $SettingsObject.$SettingsFile
- *changing it to Object instead of striping it out completely

2020-12-23 15:17 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +						$interimPath = Resolve-FilePath -NestedFile $ymlObject
done

2020-12-24 13:22 UTC, tm-luke requested changes

2020-12-24 13:22 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/New-CmAzProject.ps1
>  		New-Item -Path $Project -ItemType Directory -Force | Out-Null
"> $null"

2020-12-24 13:22 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +				$fullProjectRootPath = (Get-Item $ProjectRoot).FullName
Why are we fetching the root again here?

2020-12-24 13:22 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +						$YmlFilePath,
I would argue this is a directory path

2020-12-24 13:22 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +					if (!$interimPath.contains('.yml')){
Is it worth adding this as an optional argument to resolve path? Have an extra param that contains the file extension and if its not null then the file extension is added on if it isnt already there.

2020-12-24 15:10 UTC, tm-luke approved these changes

2020-12-24 15:10 UTC, merged