Iaas - Network script to support vnet peering
Trustmarque/cloudmarque-azure-pwsh pull request #168
Opened 2020-12-24 14:14 UTC by deepend-dev

resolved #159

2021-01-05 10:49 UTC, tm-luke requested changes

2021-01-05 10:49 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +				$fullProjectRootPath = (Get-Item $ProjectRoot).FullName
Is this to handle relative paths? Is an exception thrown if the full path is used for get-item?

2021-01-05 10:49 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +				$fullProjectRootPath = (Get-Item $ProjectRoot).FullName
Looks like you are doing the same above at line 83

2021-01-05 10:49 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +							sourceVnetRg           = ($resourceGroupObjectArray | Where-Object { $_.vnets.vnetname -eq $Vnet.vnetname }).resourceGroup.name
Looks like $_.vnets.vnetname could be a collection, which wouldn't equal the vnet.vnetname

2021-01-05 10:49 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +							TargetVnetRg           = ($resourceGroupObjectArray | Where-Object { $_.vnets.vnetname -eq $peeringVnet }).resourceGroup.name
Where-Object { $_.vnets.vnetname -eq $peeringVnet }) is being done on two lines, can you store this collection in a variable and use that instead?

2021-01-05 10:49 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/networking/yml/networking.yml
> +# All the relative paths are resolved to project root directory
the project root directory

2021-01-05 13:04 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +				$fullProjectRootPath = (Get-Item $ProjectRoot).FullName
it has already gone in with relative path branch.

2021-01-05 13:04 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +				$fullProjectRootPath = (Get-Item $ProjectRoot).FullName
same as above.

2021-01-05 13:06 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +							sourceVnetRg           = ($resourceGroupObjectArray | Where-Object { $_.vnets.vnetname -eq $Vnet.vnetname }).resourceGroup.name
no it cann't because we are filtering through object created by us which makes sure there is only one vnet per vnetName

2021-01-05 13:07 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +							TargetVnetRg           = ($resourceGroupObjectArray | Where-Object { $_.vnets.vnetname -eq $peeringVnet }).resourceGroup.name
not it is just being done once...

2021-01-05 13:08 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/networking/yml/networking.yml
> +# All the relative paths are resolved to project root directory
done

2021-01-05 13:08 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +				$fullProjectRootPath = (Get-Item $ProjectRoot).FullName
Ok, is an exception thrown if the full path is used for get-item?

2021-01-05 13:09 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +				$fullProjectRootPath = (Get-Item $ProjectRoot).FullName
This can be removed still if this is unnecessarily repeating code.

2021-01-05 13:10 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +							sourceVnetRg           = ($resourceGroupObjectArray | Where-Object { $_.vnets.vnetname -eq $Vnet.vnetname }).resourceGroup.name
Might be worth storing the found resourcegroup name in a separate variable to avoid this confusion in the future.

2021-01-05 13:12 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +				$fullProjectRootPath = (Get-Item $ProjectRoot).FullName
no it is not required.. the intention is to capture full path even if short is provided ..

2021-01-05 13:14 UTC, tm-luke requested changes

2021-01-05 13:14 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +							TargetVnetRg           = ($resourceGroupObjectArray | Where-Object { $_.vnets.vnetname -eq $peeringVnet }).resourceGroup.name
Ah my mistake, looks like the lines 962 and 963 were essentially the same. But one is at the rg level and the other is at the vnet level.

2021-01-05 13:26 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +							sourceVnetRg           = ($resourceGroupObjectArray | Where-Object { $_.vnets.vnetname -eq $Vnet.vnetname }).resourceGroup.name
$getCurrentVnetObject = $resourceGroupObjectArray | Where-Object { $_.vnets.vnetname -eq $Vnet.vnetname }

sourceVnetRg  = $getCurrentVnetObject.resourceGroup.name

2021-01-06 12:58 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +				$fullProjectRootPath = (Get-Item $ProjectRoot).FullName
done as discussed

2021-01-06 14:19 UTC, tm-luke approved these changes

2021-01-06 14:23 UTC, tm-luke approved these changes

2021-01-06 14:42 UTC, merged