New-CmAzIaasNetworking -  allow route propagation
Trustmarque/cloudmarque-azure-pwsh pull request #179
Opened 2021-01-15 11:25 UTC by deepend-dev

resolves #177

2021-01-15 14:45 UTC, tm-luke approved these changes

2021-01-15 14:45 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +					$routePropagation = switch ($routePropagation) {
Is $routePropagation a string?

2021-01-15 14:45 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +					$routePropagation = switch ($routePropagation) {
Might be worth trying to cast the string value instead

2021-01-15 14:46 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +					$routePropagation = switch ($routePropagation) {
the problem is $routePropagation for csv is string and for yml is boolean ..

2021-01-15 14:46 UTC, tm-luke requested changes

2021-01-15 14:46 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
> +					$routePropagation = switch ($routePropagation) {
I think .net has a tryparse method for this stuff

2021-01-16 00:04 UTC, tm-luke approved these changes

2021-01-16 00:04 UTC, merged