New-CmAzDeployment -  initial implementation
Trustmarque/cloudmarque-azure-pwsh pull request #184
Opened 2021-01-22 09:58 UTC by deepend-dev

closes #91

2021-01-22 10:43 UTC, tm-luke requested changes
Initial review, will look more after.

2021-01-22 10:43 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/New-CmAzDeployment.ps1
> +         Object containing the configuration values required to run this cmdlet.
Are these aligned in code?

2021-01-22 10:43 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/New-CmAzDeployment.ps1
> +        [parameter(Mandatory = $false)]
Are these aligned in code?

2021-01-22 10:43 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/New-CmAzDeployment.ps1
> +            switch ($SettingsObject.component) {
is this case insensitive?

2021-01-22 10:43 UTC, tm-luke commented on Cloudmarque.Azure/Private/Utility/Get-Prerequisites.ps1
> +    Write-Verbose "Invoking $CommandName"
Can we add more info from Get-AzContext to "Invoking $CommandName"?

2021-01-22 10:43 UTC, tm-luke commented on Cloudmarque.Azure/Private/Utility/Get-Prerequisites.ps1
> +    Get-CmAzSubscriptionName
I think this should be separate from the command, as Get-Prerequisites should output invoke information

2021-01-25 09:35 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/New-CmAzDeployment.ps1
> +        [parameter(Mandatory = $false)]
yes

2021-01-25 09:35 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/New-CmAzDeployment.ps1
> +            switch ($SettingsObject.component) {
yes

2021-01-25 14:09 UTC, tm-luke requested changes

2021-01-25 14:23 UTC, deepend-dev commented on Cloudmarque.Azure/Private/Utility/Get-Prerequisites.ps1
> +    Write-Verbose "Invoking $CommandName"
we decided on friday that we will just do verbose message - "invoke command" only

2021-01-27 11:00 UTC, closed without merging