New-CmAzDeployment first implementation
Trustmarque/cloudmarque-azure-pwsh pull request #186
Opened 2021-01-25 15:13 UTC by deepend-dev

resolves #91

2021-01-25 16:24 UTC, tm-luke requested changes

2021-01-25 16:24 UTC, tm-luke commented on azure-pipelines.yml
> -- name: ReleaseNotes
revert indentation

2021-01-25 16:24 UTC, tm-luke commented on Tests/New-CmAzDeployment.Tests.ps1
> +    Context "Component identified successfully" {
Cmdlet instead of component

2021-01-25 16:24 UTC, tm-luke commented on Tests/New-CmAzDeployment.Tests.ps1
> +        It "should be able to call associated command for <_.Filename>" -TestCases $resourceFiles {
the correctly associated command for <_.Filename>"

2021-01-25 16:24 UTC, tm-luke commented on Tests/New-CmAzDeployment.Tests.ps1
> +                New-CmAzDeployment -SettingsFile "$PSScriptRoot\..\Cloudmarque.Azure\Resources\Project\security.yml" -whatif
-WhatIf

2021-01-25 16:24 UTC, tm-luke commented on Tests/New-CmAzDeployment.Tests.ps1
> +                    $deployments = New-CmAzDeployment -SettingsFile $_.Path -LocalAdminUsername $username -LocalAdminPassword $password -whatif -verbose 4>&1 -Erroraction continue
-WhatIf, -Verbose

2021-01-25 16:24 UTC, tm-luke commented on Tests/New-CmAzDeployment.Tests.ps1
> +                }
Why are we using ErrorAction continue here?

2021-01-25 16:24 UTC, tm-luke commented on Tests/New-CmAzDeployment.Tests.ps1
> +            } | Should -Not -Throw "Please provide appropriate component value in settings file or object.."
Store message in a variable and reuse across tests

2021-01-25 16:24 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Security/security-centre/Set-CmAzSecurityCentre.ps1
> +		if ($PSCmdlet.ShouldProcess((Get-CmAzSubscriptionName), "Deploy Security Centre")) {
Is this correctly indented?

2021-01-25 16:24 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Security/managed-services/New-CmAzSecurityPartner.ps1
> +        Get-InvocationInfo -CommandName $MyInvocation.MyCommand.Name
Is this correctly indented?

2021-01-25 16:24 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/PaaS/sharedImageGallery/New-CmAzPaasSharedImageGallery.ps1
> +		if ($PSCmdlet.ShouldProcess((Get-CmAzSubscriptionName), "Deploy shared image gallery")) {
Is this correctly indented?

2021-01-25 16:24 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/vm/Set-CmAzIaasUpdateManagement.ps1
revert indentation

2021-01-26 09:47 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/recoveryvault.yml
> +  - name: Iaas-Test-Rec-Vault1
done

2021-01-26 09:47 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/monitor.yml
> +  - name: Core-Test-Ag1
done

2021-01-26 09:48 UTC, deepend-dev commented on azure-pipelines.yml
> -- name: ReleaseNotes
done

2021-01-26 09:49 UTC, deepend-dev commented on Tests/New-CmAzDeployment.Tests.ps1
> +    Context "Component identified successfully" {
resolved

2021-01-26 09:50 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/PaaS/sharedImageGallery/New-CmAzPaasSharedImageGallery.ps1
> +		if ($PSCmdlet.ShouldProcess((Get-CmAzSubscriptionName), "Deploy shared image gallery")) {
no looks good

2021-01-26 09:51 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/New-CmAzDeployment.ps1
> +
yes

2021-01-26 09:52 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/New-CmAzDeployment.ps1
> +        [Object]$SettingsObject,
yes

2021-01-26 09:53 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/New-CmAzDeployment.ps1
> +			if ($SettingsFile -and !$SettingsObject) {
corrected

2021-01-26 09:54 UTC, deepend-dev commented on Tests/New-CmAzDeployment.Tests.ps1
> +        It "should be able to call associated command for <_.Filename>" -TestCases $resourceFiles {
done

2021-01-26 09:54 UTC, deepend-dev commented on Tests/New-CmAzDeployment.Tests.ps1
> +                New-CmAzDeployment -SettingsFile "$PSScriptRoot\..\Cloudmarque.Azure\Resources\Project\security.yml" -whatif
done

2021-01-26 09:55 UTC, deepend-dev commented on Tests/New-CmAzDeployment.Tests.ps1
> +                    $deployments = New-CmAzDeployment -SettingsFile $_.Path -LocalAdminUsername $username -LocalAdminPassword $password -whatif -verbose 4>&1 -Erroraction continue
done

2021-01-26 09:56 UTC, deepend-dev commented on Tests/New-CmAzDeployment.Tests.ps1
> +                }
for further tests to continue even if the some of the tests fail

2021-01-26 09:57 UTC, deepend-dev commented on Tests/New-CmAzDeployment.Tests.ps1
> +            } | Should -Not -Throw "Please provide appropriate component value in settings file or object.."
done

2021-01-26 09:58 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Security/security-centre/Set-CmAzSecurityCentre.ps1
> +		if ($PSCmdlet.ShouldProcess((Get-CmAzSubscriptionName), "Deploy Security Centre")) {
yes

2021-01-26 09:58 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Security/managed-services/New-CmAzSecurityPartner.ps1
> +        Get-InvocationInfo -CommandName $MyInvocation.MyCommand.Name
yes

2021-01-26 10:02 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/vm/Set-CmAzIaasUpdateManagement.ps1
there is none

2021-01-26 11:29 UTC, tm-luke requested changes

2021-01-26 11:29 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/New-CmAzDeployment.ps1
> +
Synopsis should be a brief overview, description needs to be in-depth explanation of what the cmdlet does.

2021-01-26 11:29 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/New-CmAzDeployment.ps1
> +
Make sure the text under the documentation text is aligned with their headers

2021-01-26 11:29 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Security/managed-services/New-CmAzSecurityPartner.ps1
> +			if ($SettingsFile -and !$SettingsObject) {
Looks like this is more indented in relation to its containing if statement

2021-01-26 11:29 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/monitor.yml
> +    - emailAddress: testActionGroup1@Cloudmarque.com
Undo indentation

2021-01-26 11:29 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/monitor.yml
> +    - functionAppResourceId: Core-Test-Func-Res-Id
Undo indentation

2021-01-26 11:29 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/monitor.yml
> +    - resourceId: Core-Test-Logic-ResId
Undo indentation

2021-01-26 11:29 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/monitor.yml
> -  - serviceUri: https://CoreTestWbSvUri
Undo indentation

2021-01-26 11:29 UTC, tm-luke commented on Tests/New-CmAzDeployment.Tests.ps1
> +                }
Does it still highlight every test that has failed with the continue?

2021-01-26 11:29 UTC, tm-luke commented on Tests/New-CmAzDeployment.Tests.ps1
> +    Context "Cmdlet  is successfully identified" {
Remove unneeded space.

2021-01-26 11:29 UTC, tm-luke commented on azure-pipelines.yml
> +    - job:
Undo indentation

2021-01-26 11:29 UTC, tm-luke commented on azure-pipelines.yml
> +    - job:
Undo changes

2021-01-26 11:29 UTC, tm-luke commented on azure-pipelines.yml
> +    - job:
Undo indentation

2021-01-26 11:29 UTC, tm-luke commented on azure-pipelines.yml
> +    - job:
Undo changes

2021-01-26 11:29 UTC, tm-luke commented on azure-pipelines.yml
> +    - deployment:
Undo changes

2021-01-27 10:27 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Security/managed-services/New-CmAzSecurityPartner.ps1
> +			if ($SettingsFile -and !$SettingsObject) {
looks fine to me

2021-01-27 10:28 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/monitor.yml
> +    - emailAddress: testActionGroup1@Cloudmarque.com
done

2021-01-27 10:29 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/monitor.yml
> +    - functionAppResourceId: Core-Test-Func-Res-Id
done

2021-01-27 10:29 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/monitor.yml
> +    - resourceId: Core-Test-Logic-ResId
done

2021-01-27 10:30 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/monitor.yml
> -  - serviceUri: https://CoreTestWbSvUri
done

2021-01-27 10:31 UTC, deepend-dev commented on Tests/New-CmAzDeployment.Tests.ps1
> +    Context "Cmdlet  is successfully identified" {
done

2021-01-27 10:33 UTC, deepend-dev commented on azure-pipelines.yml
> +    - job:
done

2021-01-27 10:33 UTC, deepend-dev commented on azure-pipelines.yml
> +    - job:
done

2021-01-27 10:33 UTC, deepend-dev commented on azure-pipelines.yml
> +    - job:
done

2021-01-27 10:33 UTC, deepend-dev commented on azure-pipelines.yml
> +    - deployment:
done

2021-01-27 10:33 UTC, deepend-dev commented on azure-pipelines.yml
> +    - job:
done

2021-01-27 10:34 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/New-CmAzCore.ps1
> +		if ($PSCmdlet.ShouldProcess((Get-CmAzSubscriptionName), "Deploy Core Monitoring and Logging")) {
no

2021-01-27 10:59 UTC, tm-luke approved these changes

2021-01-27 10:59 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/New-CmAzDeployment.ps1
> +
Wrapper function to auto-identify cmdlet to based on provided settings and deploy Azure infrastructure.

2021-01-27 10:59 UTC, merged