New-CmAzPaasFunction : Initial Implementation
Trustmarque/cloudmarque-azure-pwsh pull request #225
Opened 2021-02-15 15:37 UTC by deepend-dev

closes #183

2021-02-16 11:25 UTC, tm-luke requested changes

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/functions.yml
> +      - name: Fun-Test-Con-Win
Paas-Test-Func-Con1

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/functions.yml
> +            function: Fun-Test-Con-Win-App
Remove value

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/functions.yml
> +            appServicePlan: Fun-Test-Con-Win-Asp
Remove value

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/storage.yml
> +      storage: Iaas-Test-Function
Iaas-Test-St

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/functions.yml
> +  - name: Fun-Test-Con-Lin-Rg2
Paas-Test-Func-Rg2

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/functions.yml
> +      - name: Fun-Test-Con-Lin
Paas-Test-Func-Con2

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/functions.yml
> +            function: Fun-Test-Con-Lin-App
Paas-Test-Func2

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/functions.yml
> +            appServicePlan: Fun-Test-Con-Lin-Asp
Paas-Test-Func-Asp2

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/functions.yml
> +    service:
Paas-Test-Func-Rg3

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/functions.yml
> +      - name: Fun-Test-Win-Asp1
Paas-Test-Func-Asp1

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/functions.yml
> +          - name: Fun-Test-Win-App3
Paas-Test-Func3

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/functions.yml
> +  - name: Fun-Asp-Lin-Rg4
Paas-Test-Func-Rg4

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/functions.yml
> +      - name: Fun-Test-Lin-Asp2
Paas-Test-Func-Asp2

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/functions.yml
> +          - name: Fun-Test-Lin-App4
Paas-Test-Func4

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/web.yml
> +    function: Web-Test-Fun-App1
Web-Test-Func

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/web.yml
> +    storage: Iaas-Test-Function                               # For function apps
Iaas-Test-Func

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/web.yml
> +    - name: Web-Test-Fun-App1
Web-Test-Func1

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +					"additionalProperties": true
Should be false

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +					"additionalProperties": true
Should be false

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +			"additionalItems": true,
Remove this.

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +			"items": {
Add minitems property set to 1

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +				"anyOf": [
If this is one schema, set to allOf instead of anyOf

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +						"$id": "#/functionAppSolutions/items/anyOf/0",
Update ids to use allOf where applicable

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +						"$id": "#/functionAppSolutions/items/anyOf/0",
Remove /0

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +								"additionalItems": false,
remove this

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +											"description": "An explanation about the purpose of this instance.",
No need for title or description here

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +									"anyOf": [
Use allOf instead of anyOf, remove /0

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +												"runtime": {
Is there a preset list of accepted values for this? If so we should use an enum.

2021-02-16 11:25 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +						"title": "Second anyOf",
If the types or the fundemental structure of functionAppSolutions isn't different, you should need the second schema (ids containing anyOf/1) defined here. Default or nullable values can be handled in the first.

2021-02-16 11:46 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/PaaS/function/New-CmAzPaasFunction-consumption.json
> +                            "sku": {
thats a hard coded sku for consumption type plan

2021-02-16 11:55 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/PaaS/function/New-CmAzPaasFunction-appServicePlan.json
> +                            "kind": "[if(equals(parameters('appServiceObject').kind, 'linux'), 'linux', '')]",
it can either be linux or empty string

2021-02-16 11:56 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/PaaS/function/New-CmAzPaasFunction-appServicePlan.json
> +                                            "name": "[parameters('functionAppObject').functionGeneratedName]",
we get generated name after passing name through Get-CmAzResourceName

2021-02-16 11:57 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/PaaS/function/New-CmAzPaasFunction-appServicePlan.json
> +                                                            "value": "[concat('DefaultEndpointsProtocol=https;AccountName=', parameters('functionAppObject').storageAccount.Name, ';AccountKey=', listK
done

2021-02-16 12:04 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/PaaS/function/New-CmAzPaasFunction.ps1
> +        if ($PSCmdlet.ShouldProcess((Get-CmAzSubscriptionName), "Deploy Azure - Functions")) {
done

2021-02-16 12:05 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/PaaS/function/New-CmAzPaasFunction.ps1
> +                if (!$functionAppSolution.transFrmWeb) {
that function app is called from webstack

2021-02-16 12:15 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/PaaS/web/New-CmAzPaasWeb.ps1
> +										}
yes

2021-02-16 12:17 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/storage.yml
> +      storage: Iaas-Test-Function
we want to use this storage for functions app

2021-02-16 12:17 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/functions.yml
> +    storage: Iaas-Test-Function
we want to use a particular storage account from Iaas... its not a core storage account requirement

2021-02-16 12:21 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasWeb.Schema.json
> +                        "additionalProperties": true
yes, it is required to be able to pass object from web

2021-02-16 12:21 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasWeb.Schema.json
> +                        "additionalProperties": true
we have only did it at top level, the relevant object is still checked before being processed for functions

2021-02-16 12:24 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +					"additionalProperties": true
required to allow object being passed from web

2021-02-16 12:24 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +					"additionalProperties": true
required

2021-02-16 12:25 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +				"anyOf": [
it can have either consumption plan or app service plan in one rg

2021-02-16 12:44 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +						"title": "Second anyOf",
this is to make sure we got two options in rg - either appserviceplan or consumptionplan

2021-02-16 14:00 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/web.yml
> +    storage: Iaas-Test-Function                               # For function apps
specific storage required

2021-02-16 14:03 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +					"description": "Contains dependency and publish details for service location.",
done

2021-02-16 14:04 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/PaaS/web/New-CmAzPaasWeb.ps1
> +										}
removed

2021-02-16 14:12 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
> +												"runtime": {
no there are just too many

2021-02-17 09:59 UTC, tm-luke approved these changes

2021-02-17 09:59 UTC, merged