Auto-Accept Marketplace terms
Trustmarque/cloudmarque-azure-pwsh pull request #227
Opened 2021-02-18 13:32 UTC by deepend-dev

closes #182

2021-02-18 14:58 UTC, tm-luke reviewed
Can you run this in the integration pipeline?

2021-02-22 13:26 UTC, tm-luke requested changes

2021-02-22 13:26 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/networking/csv/vnet.csv
> +Iaas-Test-Hub2-Rg,UKWest,Iaas-Test-Hub2-Vnet1,10.0.0.0/23,,,Iaas-Test-Hub2-Vnet1-Snet-dc1,10.0.0.192/27,,,,
Why are we removing this?

2021-02-22 13:26 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVm.Schema.json
> +                                                            "enum": ["Windows", "Linux", "windows", "linux"]
This shouldn't be needed

2021-02-22 13:27 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVm.Schema.json
> +                                                            "enum": ["Windows", "Linux", "windows", "linux"]
It seems to be case sensitive.

2021-02-22 13:28 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/networking/csv/vnet.csv
> +Iaas-Test-Hub2-Rg,UKWest,Iaas-Test-Hub2-Vnet1,10.0.0.0/23,,,Iaas-Test-Hub2-Vnet1-Snet-dc1,10.0.0.192/27,,,,
to get one subnet access internet so that omsagnt can install

2021-02-22 13:58 UTC, tm-luke approved these changes

2021-02-22 18:08 UTC, merged