Multi-sub peering initial implementation
Trustmarque/cloudmarque-azure-pwsh pull request #268
Opened 2021-04-15 15:45 UTC by deepend-dev

resolves below -
#206
#259

2021-04-19 14:38 UTC, tm-luke requested changes

2021-04-19 14:38 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/Get-CmAzResourceName.ps1
> +			$regionConvention ??= $regions.regions | Where-Object { $_.alias -contains $Region }
Is this needed, with the line above?

2021-04-19 14:38 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/vnetPeerings/New-CmAzIaasVnetPeerings.json
> +                        "VnetPeeringsObject": {
Remove object from name

2021-04-19 14:38 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/vnetPeerings/New-CmAzIaasVnetPeerings.ps1
> +        $azContext = Get-AzContext
Move below what-if check

2021-04-19 14:38 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/vnetPeerings/New-CmAzIaasVnetPeerings.ps1
> +		if ($PSCmdlet.ShouldProcess((Get-CmAzSubscriptionName), "Create Vnet Peerings")) {
Create vnet peerings

2021-04-19 14:38 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/vnetPeerings/New-CmAzIaasVnetPeerings.ps1
> +			Write-Verbose "Finished."
Finished!

2021-04-19 14:38 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/Integration/vnetPeerings.yml
> +  - source:
Remove indent for all arrays

2021-04-19 14:38 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVnetPeerings.Schema.json
> +			"items": {
Add minItems: 1 to item section

2021-04-19 14:38 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVnetPeerings.Schema.json
> +								"items": {
Add minItems:1 to items section

2021-04-19 14:38 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVnetPeerings.Schema.json
> +												"resourceGroup": {
Isnt resourceGroup optional?

2021-04-19 14:53 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Common/Get-CmAzResourceName.ps1
> +			$regionConvention ??= $regions.regions | Where-Object { $_.alias -contains $Region }
yes as it search in alias as well if the name doesnt match. that is how alias should be working earlier but that code was missing

2021-04-19 14:53 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVnetPeerings.Schema.json
> +												"resourceGroup": {
nope

2021-04-19 15:01 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/Get-CmAzResourceName.ps1
> +			$regionConvention ??= $regions.regions | Where-Object { $_.alias -contains $Region }
It should probably be $regions.regions | Where-Object { $_.name -Eq $Region -or $.alias -Eq $Region }

2021-04-20 13:13 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Common/Get-CmAzResourceName.ps1
> +			$regionConvention ??= $regions.regions | Where-Object { $_.alias -contains $Region }
done

2021-04-20 13:14 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/vnetPeerings/New-CmAzIaasVnetPeerings.json
> +                        "VnetPeeringsObject": {
done

2021-04-20 13:14 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/vnetPeerings/New-CmAzIaasVnetPeerings.ps1
> +        $azContext = Get-AzContext
done

2021-04-20 13:14 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/vnetPeerings/New-CmAzIaasVnetPeerings.ps1
> +		if ($PSCmdlet.ShouldProcess((Get-CmAzSubscriptionName), "Create Vnet Peerings")) {
done

2021-04-20 13:14 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/vnetPeerings/New-CmAzIaasVnetPeerings.ps1
> +			Write-Verbose "Finished."
done

2021-04-20 13:14 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/Integration/vnetPeerings.yml
> +  - source:
done

2021-04-20 13:14 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVnetPeerings.Schema.json
> +			"items": {
done

2021-04-20 13:14 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVnetPeerings.Schema.json
> +								"items": {
done

2021-04-20 13:15 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVnetPeerings.Schema.json
> +												"resourceGroup": {
you are right. updated

2021-04-20 18:20 UTC, tm-luke approved these changes

2021-04-21 08:55 UTC, merged