Iaas networking service endpoint support
Trustmarque/cloudmarque-azure-pwsh pull request #283
Opened 2021-04-27 16:43 UTC by deepend-dev

closes #276 by providing service endpoint support in both csv and yml versions

2021-05-05 11:26 UTC, tm-luke requested changes

2021-05-06 08:05 UTC, deepend-dev commented on azure-integration-pipelines.yml
> +          New-CmAzDeployment -SettingsFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/Integration/networking/yml/example/networking.yml" -Verbose -Confirm:$false
done

2021-05-06 08:05 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/Integration/networking/yml/example/vnets/Iaas-Test-Spoke1-Vnet1.yml
> +dnsServers: ''
no we donot. Its all autogenerated

2021-05-06 08:06 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/managedNetwork/New-CmAzIaasNetworking.ps1
> +											if ($endpoint -ne '') {
ok will do

2021-05-06 08:11 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/managedNetwork/New-CmAzIaasNetworking.ps1
> +							if ($_ -ne '') {
done

2021-05-06 09:00 UTC, tm-luke approved these changes

2021-05-06 09:02 UTC, merged