New-CmAzIaasFirewalls first implementation
Trustmarque/cloudmarque-azure-pwsh pull request #324
Opened 2021-06-29 09:04 UTC by deepend-dev

2021-06-29 11:36 UTC, tm-luke requested changes

2021-06-29 11:36 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasFirewalls.Schema.json
> +                            "location": {
Is there a default value here? if so we need to add the default property here

2021-06-29 11:36 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +		 Completes following:
Completes the following:

2021-06-29 11:36 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +		 Creates Firewall and Firewall policies.
Creates multiple firewalls and policies

2021-06-29 11:36 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +			if ($SettingsObject.firewallPolicies) {
I dont think you need a null check before a foreach

2021-06-29 11:36 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +			if ($SettingsObject.firewalls) {
I dont think you need a null check before the foreach

2021-06-29 11:36 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +					if ($SettingsObject.firewallPolicies.service.publish.firewallPolicy.contains($firewall.service.dependencies.firewallPolicy)){
space between ) {

2021-06-29 11:36 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +					if ($SettingsObject.firewallPolicies.service.publish.firewallPolicy.contains($firewall.service.dependencies.firewallPolicy)){
Do we need the contains check, when we are doing the same thing below?

2021-06-29 11:36 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +						if ($firewall.firewallPolicyService -is [array]){
) {

2021-06-29 11:36 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +							Write-Error "Multiple firewall policies have same tags. Please provide unique service tag."
Can you pass in the same parameters we use in other Write-Error instances?

2021-06-29 12:23 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Set-CmAzTag.ps1
> +					'Microsoft.Network/azureFirewalls' {
its microsoft syntax

2021-06-29 12:24 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Set-CmAzTag.ps1
> +						Set-AzFirewallPolicy -ResourceId $resource.Id -Location $resource.location -Tag $tagsToSet > $null
it doesnt work for policy. throws http patch is not acceptable

2021-06-29 12:27 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasFirewalls.Schema.json
> +            "description": "Container for Firewalls configuration details.",
but the config name in yml is firewalls

2021-06-29 12:37 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasFirewalls.Schema.json
> +                                "description": "Becomes part of private endpoint name."
done

2021-06-29 12:37 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasFirewalls.Schema.json
> +                                "description": "Becomes AzureFirewallSubnet cidr"
done

2021-06-29 12:38 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasFirewalls.Schema.json
> +                                "description": "Firewall Sku"
done

2021-06-29 12:38 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasFirewalls.Schema.json
> +            "type": ["array", "null"],
not mandatory//

2021-06-29 12:38 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasFirewalls.Schema.json
> +                            "location": {
nope

2021-06-29 12:38 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasFirewalls.Schema.json
> +            "type": ["array", "null"],
not mandatory. can just create policy as well

2021-06-29 12:39 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +		 Creates Firewall and Firewall policies.
done

2021-06-29 12:39 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +		 Completes following:
Done

2021-06-29 12:40 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +			if ($SettingsObject.firewallPolicies) {
we need it for deployment script any ways

2021-06-29 12:40 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +			if ($SettingsObject.firewalls) {
needed for optional deployment

2021-06-29 13:17 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasFirewalls.Schema.json
> +                                "description": "Becomes AzureFirewallSubnet cidr"
done

2021-06-29 13:17 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasFirewalls.Schema.json
> +                                "description": "Firewall Sku"
done

2021-06-29 13:18 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasFirewalls.Schema.json
> +            "type": ["array", "null"],
its optional

2021-06-29 13:18 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzIaasFirewalls.Schema.json
> +            "type": ["array", "null"],
its optional

2021-06-30 10:36 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/Integration/firewalls.yml
> +    resourceGroup: Iaas-Firewall-Rg
done

2021-06-30 10:36 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/Integration/firewalls.yml
> +- name: Iaas-Firewall-Policy-1
done

2021-06-30 10:37 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +							Write-Error "Multiple firewall policies have same tags. Please provide unique service tag."
done

2021-06-30 10:37 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +						if ($firewall.firewallPolicyService -is [array]){
done

2021-06-30 10:37 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +					if ($SettingsObject.firewallPolicies.service.publish.firewallPolicy.contains($firewall.service.dependencies.firewallPolicy)){
done

2021-06-30 10:38 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +							Write-Error "Multiple firewall policies have same tags. Please provide unique service tag."
done

2021-07-13 09:44 UTC, tm-luke requested changes

2021-07-14 10:34 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewallPolicies.json
> +
Done

2021-07-14 10:36 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewallPolicies.json
> +                "template": {
Policy and firewall dont have 1-2-1 mapping. There can be multiple firewalls per policy. There can be scenarios where only policy or only firewalls are configured.. Also the dependency management was getting complicated with single template.

2021-07-14 10:37 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewallPolicies.json
> +                        {   "condition": "[not(equals(parameters('FirewallPolicy').ruleCollectionGroups[0].name, 'none'))]",
No. We have discussed this before. Azure variable validation happens before condition or copy check. And it expects those variables to be valid specially for name of resource.

2021-07-14 10:38 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.json
> +
done

2021-07-14 10:39 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.json
> +            "type": "Microsoft.Resources/Deployments",
same reason as above

2021-07-14 10:39 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.json
> +            "name": "[take(concat('cm_fw_', parameters('Firewalls')[copyIndex('FirewallsCopy')].name, copyIndex('FirewallsCopy')), 64)]",
done

2021-07-14 10:40 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.json
> +                                "publicIPAllocationMethod": "Static"
No

2021-07-14 10:41 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +				$firewallPolicy.threatIntelWhitelist ??= @{ipAddresses = @(); fqdns = @() }
done

2021-07-14 10:41 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +							$ruleCollection.actionType ??= "Dnat"
Its is not. I have just used Microsoft syntax

2021-07-14 10:41 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +					$firewallPolicy.ruleCollectionGroups = @(@{name = 'none'; ruleCollections = @() })
done

2021-07-14 10:42 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +				}
done

2021-07-14 10:43 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
> +				$location = $SettingsObject.firewallPolicies[0].location
it is not possible to deploy firewall without policy but tt is not possible that policy is not defined in same yml template..

2021-07-14 10:45 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/Integration/networking/firewall/firewalls.yml
> +  - ./networking/firewall/rulesCollection/alpha.yml
done

2021-07-14 10:47 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/Integration/networking/firewall/rulesCollection/alpha.yml
> +      - protocolType: Http
nope.. its complete random and application dependant.

2021-07-14 10:47 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/Integration/networking/firewall/rulesCollection/alpha.yml
> +        -  Any
done

2021-07-14 10:48 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/Integration/networking/firewall/rulesCollection/alpha.yml
> +# 2. Priority order of rules should be: DNAT>Network>Application.
done

2021-07-14 10:49 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/Integration/networking/firewall/rulesCollection/alpha.yml
> +  # - name: Iaas-RuleCollection-Dnat
its there

2021-07-14 10:52 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/Subschema/New-CmAzIaasFirewalls.RuleCollectionGroups.SubSchema.json
> +                                "type": ["number"],
done

2021-07-14 10:53 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/Subschema/New-CmAzIaasFirewalls.RuleCollectionGroups.SubSchema.json
> +                                                                        "$id": "#/ruleCollectionGroups/items/allOf/ruleCollections/items/allOf/rules/items/oneOf/network/ipProtocols",
its an array

2021-07-14 11:20 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/Subschema/New-CmAzIaasFirewalls.RuleCollectionGroups.SubSchema.json
> +    "": "http://json.org/draft-07",
unfortunately its doesnt work..  It seems Test-Json has limitation.. Might require more time to troubleshoot. For now I have done it separately for both deployments variations.

2021-07-14 14:33 UTC, tm-luke requested changes

2021-07-14 14:33 UTC, tm-luke commented on Cloudmarque.Azure/Private/Utility/Get-InvocationInfo.ps1
> +function Get-InvocationInfo() {
revert this change

2021-07-14 14:33 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewallPolicies.json
> +                        {   "condition": "[not(equals(parameters('FirewallPolicy').ruleCollectionGroups[0].name, 'none'))]",
Yeah for names, but not when its a copy section i dont think

2021-07-14 14:33 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewallPolicies.json
> +                        {   "condition": "[not(equals(parameters('FirewallPolicy').ruleCollectionGroups[0].name, 'none'))]",
Might be worth double checking if you need that check, my think is if its a section thats copied, then the name shouldnt be checked early

2021-07-14 14:33 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.json
> +                                "publicIPAllocationMethod": "Static"
As in, no for publicIPAddresses? or for when theyre used in tandem with firewalls

2021-07-14 15:21 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewallPolicies.json
> +                        {   "condition": "[not(equals(parameters('FirewallPolicy').ruleCollectionGroups[0].name, 'none'))]",
I have check it .. It was previously empty array.. I had to change to name = none because it failed .. name gets evaluated irrespective of condition

2021-07-14 15:22 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.json
> +                                "publicIPAllocationMethod": "Static"
when they are used in tandem with firewalls.

2021-07-14 15:27 UTC, tm-luke approved these changes

2021-07-15 08:57 UTC, deepend-dev commented on Cloudmarque.Azure/Private/Utility/Get-InvocationInfo.ps1
> +function Get-InvocationInfo() {
done

2021-07-19 16:35 UTC, tm-luke approved these changes

2021-07-19 16:35 UTC, merged