Core add new cm az custom extension
Trustmarque/cloudmarque-azure-pwsh pull request #342
Opened 2021-07-30 08:44 UTC by deepend-dev

closes #321 

+ added secureDependency feature which allows user to use keyvault to pass in secure strings

2021-07-31 19:51 UTC, tm-luke requested changes
Initial review, pending demo and additional context

2021-07-31 19:51 UTC, tm-luke commented on Cloudmarque.Azure/Private/Utility/Resolve-FilePath.ps1
> +
This isn't the place to check if the file referenced is an extension, as this is intended to resolve relative paths.

Additionally the relative check can be done with the following method [System.IO.Path]::IsPathRooted($_)

2021-07-31 19:51 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +		if ($PSCmdlet.ShouldProcess((Get-CmAzSubscriptionName), "Create Private Endpoints")) {
Change to Deploy Custom Extension

2021-07-31 19:51 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +				$SettingsObject.names.$name.generatedName = Get-CmAzResourceName -Resource $SettingsObject.names.$name.resource `
Move -Resource parameter to newline like the others

2021-07-31 19:51 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +								$templateParameter += @{$parameter = $resolvedDependency.$property }
Add space after @{

2021-07-31 19:51 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +							if (!$secretName){
) {

2021-07-31 19:51 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +						default { Write-Error "Provided parameter type for $parameter is $($type).`nType can be name, static, secureDependency or dependency..." -Category InvalidArgument -TargetObject $type }
Would this be covered by the schema check?

2021-07-31 19:51 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +				$templatePath = Resolve-FilePath -NestedFile $template.name -istemplate
IsTemplate

2021-08-02 13:58 UTC, tm-luke requested changes

2021-08-02 13:58 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +							Write-Verbose "Working on static value: $value..."
Just use Static value: $value...

2021-08-02 13:58 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +								$resolvedDependency = Get-CmAzService -Service $value `
Move -Service to new line

2021-08-02 13:58 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +							if ($template.parameters.$parameter.location) {
The dependency retrieval code should move to an internal function in this file.

2021-08-02 13:58 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +					New-AzResourceGroupDeployment -Name $deploymentName `
Move -name to newline

2021-08-02 13:58 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +					if (!$template.location){
This should be covered by schema i think

2021-08-02 13:58 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +					New-AzResourceGroupDeployment -Name $deploymentName `
Move -name to new line

2021-08-02 13:58 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzCustomExtension.Schema.json
> +            ],
Condense to one line like the other files

2021-08-02 13:58 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzCustomExtension.Schema.json
> +            "description": "All details required to deploy multiple action groups."
I think the description needs updating.

2021-08-02 13:58 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzCustomExtension.Schema.json
> +            "description": "All details required to deploy multiple action groups.",
Same as above

2021-08-02 13:58 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzCustomExtension.Schema.json
> +                                                "type": "string"
Secrets are optional arn't they

2021-08-03 10:35 UTC, deepend-dev commented on Cloudmarque.Azure/Private/Utility/Resolve-FilePath.ps1
> +
done

2021-08-03 10:49 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +		if ($PSCmdlet.ShouldProcess((Get-CmAzSubscriptionName), "Create Private Endpoints")) {
done

2021-08-03 10:49 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +				$SettingsObject.names.$name.generatedName = Get-CmAzResourceName -Resource $SettingsObject.names.$name.resource `
done

2021-08-03 10:50 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +								$templateParameter += @{$parameter = $resolvedDependency.$property }
done

2021-08-03 10:50 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +							if (!$secretName){
done

2021-08-03 10:50 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +						default { Write-Error "Provided parameter type for $parameter is $($type).`nType can be name, static, secureDependency or dependency..." -Category InvalidArgument -TargetObject $type }
yes. removed

2021-08-03 10:51 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +				$templatePath = Resolve-FilePath -NestedFile $template.name -istemplate
rmd

2021-08-03 10:51 UTC, deepend-dev commented on Cloudmarque.Azure/Private/Utility/Resolve-FilePath.ps1
> +        $resolvedFilePath = $NestedFile
done

2021-08-03 10:51 UTC, deepend-dev commented on Cloudmarque.Azure/Private/Utility/Resolve-FilePath.ps1
> +            if ($NestedFile.contains(":") -or $NestedFile.StartsWith("/")) {
done

2021-08-03 10:52 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +					if (!$value -or !$type) {
not required as covered by schema

2021-08-03 10:54 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +							Write-Verbose "Working on static value: $value..."
done

2021-08-03 10:55 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +						"static" {
doesnt matter as it will be taken by schema anyways

2021-08-03 10:55 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +							Write-Verbose "Working on dependency value: $value..."
same

2021-08-03 10:55 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +							$template.parameters.$parameter.throwIfMultiple ??= $true
it doesnt do anything

2021-08-03 10:55 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +							$template.parameters.$parameter.throwIfMultiple ??= $true
i have changed it though

2021-08-03 10:59 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +								$resolvedDependency = Get-CmAzService -Service $value `
done

2021-08-03 10:59 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +								$resolvedDependency = Get-CmAzService -Service $value `
done

2021-08-03 11:00 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +							if ($template.parameters.$parameter.location) {
it just comes up twice

2021-08-03 11:00 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +					New-AzResourceGroupDeployment -Name $deploymentName `
done

2021-08-03 11:00 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +					if (!$template.location){
not mandatory

2021-08-03 11:02 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +					New-AzResourceGroupDeployment -Name $deploymentName `
done

2021-08-03 11:04 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzCustomExtension.Schema.json
> +            "description": "All details required to deploy multiple action groups."
done

2021-08-03 11:04 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzCustomExtension.Schema.json
> +            ],
done

2021-08-03 11:04 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzCustomExtension.Schema.json
> +            "description": "All details required to deploy multiple action groups.",
done

2021-08-03 11:04 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzCustomExtension.Schema.json
> +                                                "type": "string"
they are. done

2021-08-03 13:41 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +							$template.parameters.$parameter.throwIfMultiple ??= $true
Its for documentation purposes

2021-08-03 13:42 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +							if ($template.parameters.$parameter.location) {
Even so, if there comes a time you need to change that specific code, its very easy to miss one

2021-08-03 13:43 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Schema/New-CmAzCustomExtension.Schema.json
> +                                                "type": "string"
Looks like the secret isnt nullable though

2021-08-04 08:30 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +							if ($template.parameters.$parameter.location) {
done

2021-08-04 08:31 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzCustomExtension.Schema.json
> +                                                "type": "string"
correct

2021-08-04 10:26 UTC, tm-luke requested changes

2021-08-04 10:26 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +					$templatePath = Resolve-FilePath -NestedFile $template.name
Do we need the . check in this if statement, if this is for handling fully rooted paths?

2021-08-04 10:37 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +									-ThrowIfUnavailable:$template.parameters.$parameter.throwIfUnavailable `
yes, its a switch

2021-08-04 10:37 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +									-ThrowIfUnavailable:$template.parameters.$parameter.throwIfUnavailable `
yes

2021-08-04 10:37 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +									-ThrowIfMultiple:$template.parameters.$parameter.throwIfMultiple `
yes

2021-08-04 10:37 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +									-ThrowIfMultiple:$template.parameters.$parameter.throwIfMultiple
yes

2021-08-04 10:37 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +									-ThrowIfUnavailable:$template.parameters.$parameter.throwIfUnavailable `
yes

2021-08-04 10:37 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +									-ThrowIfMultiple:$template.parameters.$parameter.throwIfMultiple `
yes

2021-08-04 10:38 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +									-ThrowIfMultiple:$template.parameters.$parameter.throwIfMultiple
yes

2021-08-04 10:57 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +					$templatePath = Resolve-FilePath -NestedFile $template.name
Im not sure i understand, if the path is rooted surely you dont need to resolve that path? Also if the path begins with . that surely implies is NOT rooted and therefore should fall to the else statement?

2021-08-04 12:38 UTC, tm-luke requested changes

2021-08-04 12:38 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +					if (Test-Path -Path $defaultPath){
Add space

2021-08-04 12:38 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +						$resolvedPath = Resolve-FilePath -NestedFile $template.name
I would just directly set templatePath instead of resolvedPath

2021-08-04 13:05 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
> +						$resolvedPath = Resolve-FilePath -NestedFile $template.name
done

2021-08-05 11:28 UTC, tm-luke approved these changes

2021-08-05 11:28 UTC, merged