Allow passing in of monitor resources
Trustmarque/cloudmarque-azure-pwsh pull request #343
Opened 2021-08-02 15:06 UTC by tm-luke

Closes #339

2021-08-02 15:23 UTC, deepend-dev submitted a review, later dismissed

2021-08-05 09:13 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.json
> +        "workspaceResourceId": "[resourceid('Microsoft.OperationalInsights/workspaces', parameters('workspaceName'))]"
I think you should also use resource group in which workspace is deployed

2021-08-05 09:24 UTC, deepend-dev requested changes

2021-08-05 09:24 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.ps1
> +				$storageService = $SettingsObject.service.dependencies.storage
verbose for existing storage?

2021-08-05 09:24 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.ps1
> +						accountType = "Standard";
I think use of semicolon can be made consistent

2021-08-05 09:24 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.ps1
> +							@{ name = "insights-logs-addonazurebackuppolicy"},
space between "}

2021-08-05 09:24 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.ps1
> +			$storageAccountId = (Get-CmAzService -Service $storageService -ThrowIfUnavailable -ThrowIfMultiple).Id
should there be location option to search storage? considering there can be core storage in multiple regions

2021-08-05 09:24 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.ps1
> +				$workspaceName = (Get-CmAzService -Service $SettingsObject.service.dependencies.workspace -ThrowIfUnavailable -ThrowIfMultiple).resourceName
location option?

2021-08-05 09:24 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/Integration/monitor.yml
>  service:
leaving a line will look good here

2021-08-05 09:24 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/Integration/monitor.yml
> +    appInsights: Core-Test-Ai                                         # Can use publish or dependency variants of these values.
would be worth mentioning a note which one takes priority

2021-08-05 09:24 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzCoreMonitor.Schema.json
> +            "$id": "#/workspaceDataRetentionInDays",
storageDataRetentionInDays

2021-08-05 09:24 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Schema/New-CmAzCoreMonitor.Schema.json
> +            "title": "WorkspaceDataRetentionInDays",
storageDataRetentionInDays

2021-08-05 11:09 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.ps1
> +				$workspaceName = (Get-CmAzService -Service $SettingsObject.service.dependencies.workspace -ThrowIfUnavailable -ThrowIfMultiple).resourceName
Bear in mind, we are trying to link to an existing environment with minimal setup, so id argue that the service tag is enough to identify the resource we want in this case.

2021-08-05 11:09 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.ps1
> +			$storageAccountId = (Get-CmAzService -Service $storageService -ThrowIfUnavailable -ThrowIfMultiple).Id
Bear in mind, we are trying to link to an existing environment with minimal setup, so id argue that the service tag is enough to identify the resource we want in this case.

2021-08-05 11:10 UTC, tm-luke commented on Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.json
> +        "workspaceResourceId": "[resourceid('Microsoft.OperationalInsights/workspaces', parameters('workspaceName'))]"
See below

2021-08-05 12:18 UTC, deepend-dev approved these changes

2021-08-05 12:22 UTC, merged