Iaas wvd initial implementation
Trustmarque/cloudmarque-azure-pwsh pull request #39
Opened 2020-07-23 14:49 UTC by tmshaunporter

2020-07-25 22:01 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-TemplateFile "C:\Source\cloudmarque-azure-pwsh\Cloudmarque.Azure\Public\IaaS\wvd\New-CmAzWVDHostpools.json" `
Can you swap this to a relative path with $PSScriptRoot included

2020-07-25 22:03 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Location $SettingsObject[0].workspaceLocation `
This should be set to the current workspace in the loop, unless there's a reason we are hard coding to the first workspace in the settings.

2020-07-25 22:03 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Name "New-CmAzWVD_$(Get-Date -Format 'ddMMyyHHmmss')" `
Can we use name generation here?

2020-07-25 22:03 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +		Remove-Variable Workspace
You probably don't need to use remove-variable here, as the variable in question is only set with the scope of the cmdlet you're running, so it should be removed at the end anyway.

2020-07-25 22:03 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +		Write-Verbose "Begining WVD host\s object creation."
Typo here

2020-07-25 22:04 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			New-AzWvdRegistrationInfo -ResourceGroupName $Workspace.rgName -HostPoolName $Workspace.hostpool.hostpoolName -ExpirationTime ((Get-Date).AddDays('1'))
Would it be worth making the expiration configurable?

2020-07-25 22:05 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +
Would be worth performing a check to see if the registration info is returned, if there's no info then we can throw an error describing the issue.

2020-07-25 22:10 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +
These details need to be retrieved from a Keyvault or passed in as a SecureString as a separate parameter from the settings file.

2020-07-25 22:13 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$Workspace.rgName = $wvdResourceGroupName
For future reference, the pattern is pascal case ($MyWorkspace) for parameters to the cmdlet and camel case ($myWorkspace) for all other variables.

2020-07-25 22:14 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$NetworkDetails = Get-AzResource -Name $Workspace.hostpool.hostVmVnet -ResourceType "Microsoft.Network/virtualNetworks" | Where-Object {$_.Location -EQ $Workspace.hostpool.hostVmLocation.Replace("
Should be using the service locator here

2020-07-25 22:30 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$LatestImage = Get-AzVMImageSku -Location $Workspace.hostpool.hostVmLocation -PublisherName "MicrosoftWindowsDesktop" -Offer $Workspace.hostpool.hostVmImage | Where-Object {$_.Skus -like "*-evd" -
Should add a check to ensure we are able to retrieve an image here, otherwise throw an error.

2020-07-25 22:32 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				# }
No need for the commented code here.

2020-07-25 22:33 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$Workspace.hostpool.deploymentId = Get-Date -Format "ddMMyy-HHmmss"
Unsure about the reasoning behind this line, will need to discuss.

2020-07-25 22:37 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				$Workspace.hostpool.hostVmInitialNumber = 0
Can probably set this by default now

2020-07-25 22:38 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				Get-AzVM -ResourceGroupName $Workspace.rgName -Status | Where-Object PowerState -NotLike "VM running" | Start-AzVM
Are VMs not running by default upon deployment?

2020-07-25 22:38 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				$Workspace.hostpool.hostVmInitialNumber = 0
Can probably set this by default now

2020-07-25 22:39 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Name "New-CmAzWVD_$(Get-Date -Format 'ddMMyyHHmmss')" `
Can we use name generation here?

2020-07-25 22:39 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Location $SettingsObject[0].workspaceLocation `
This should be set to the current workspace in the loop, unless there's a reason we are hard coding to the first workspace in the settings.

2020-07-25 22:40 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-TemplateFile "C:\Source\cloudmarque-azure-pwsh\Cloudmarque.Azure\Public\IaaS\wvd\New-CmAzWVDHosts.json" `
Can you swap this to a relative path with $PSScriptRoot included

2020-07-25 22:40 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-settingsObject $SettingsObject
Set to uppercase S

2020-07-25 22:42 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +            "dependsOn": ["[resourceId('Microsoft.Resources/resourceGroups', parameters('settingsObject')[copyIndex('WVDhostpoolCopy')].rgName)]"],
Looks like theres one too many pairs of [] here, starting at "resourceId" and ending at "rgName)"

2020-07-25 22:42 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                "name": "rgCopy",
Change to ResourceGroupCopy

2020-07-25 22:43 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +        "settingsObject": {
Same as the cmdlets, parameters need to be Pascal case, and variables, camel case.

2020-07-25 22:44 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                            "name": "[concat(parameters('settingsObject')[copyIndex('WVDhostpoolCopy')].hostpool.hostpoolName, '-DAG')]",
Shouldn't be hardcoding parts of names unless the resource, specifically requires it

2020-07-25 22:44 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                            "name": "[concat(parameters('settingsObject')[copyIndex('WVDhostpoolCopy')].workspaceName, '-Workspace')]",
Shouldn't be hardcoding parts of names unless the resource, specifically requires it

2020-07-25 22:46 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                                "platformUpdateDomainCount": 5
Do these need to be configurable?

2020-07-25 22:46 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                                "name": "Aligned"
Does this need to be configurable?

2020-07-25 22:47 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHosts.json
> +            "type": "Array"
Same as the cmdlets, parameters need to be Pascal case, and variables, camel case.

2020-07-25 22:47 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHosts.json
> +            "name": "[concat('WVDhosts-Setup_', parameters('settingsObject')[copyIndex('WVDhostsCopy')].workspaceName)]",
Shouldn't be hardcoding parts of names unless the resource, specifically requires it

2020-07-25 22:48 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHosts.json
> +                    "uri": "https://catalogartifact.azureedge.net/publicartifacts/Microsoft.Hostpool-ARM-1.0.13-preview/managedDisks-galleryvm.json",
This looks like it should be configurable

2020-07-25 22:52 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHosts.json
> +                    //"_guidValue": {"value": "[string(parameters('settingsObject')[copyIndex('WVDhostsCopy')].hostpool.deploymentId)]"}
Remove commented line.

2020-07-25 22:56 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHosts.json
> +                    "administratorAccountPassword": {"value": "!J0inD0main123###"},//"[parameters('settingsObject')[copyIndex('WVDhostsCopy')].hostpool.hostVmAdminPass]"},
Remove commented line

2020-07-26 12:33 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +
Updated

2020-07-26 12:35 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +		Write-Verbose "Begining WVD infrastructure object creation."
Corrected

2020-07-26 12:35 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +		Write-Verbose "Depoloying WVD infrastructure."
Corrected

2020-07-26 12:36 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Name "New-CmAzWVD_$(Get-Date -Format 'ddMMyyHHmmss')" `
Name generation for what? that's the deployment name in Azure?

2020-07-26 12:37 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +		Write-Verbose "Begining WVD host\s object creation."
Corrected.

2020-07-26 12:39 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHosts.json
> +                    "administratorAccountPassword": {"value": "!J0inD0main123###"},//"[parameters('settingsObject')[copyIndex('WVDhostsCopy')].hostpool.hostVmAdminPass]"},
Removed, this was for testing.

2020-07-26 12:39 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHosts.json
> +                    //"_guidValue": {"value": "[string(parameters('settingsObject')[copyIndex('WVDhostsCopy')].hostpool.deploymentId)]"}
Removed, this was for testing.

2020-07-26 12:39 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHosts.json
> +            "name": "[concat('WVDhosts-Setup_', parameters('settingsObject')[copyIndex('WVDhostsCopy')].workspaceName)]",
This is the name of the Azure deployment.

2020-07-26 12:41 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                            "name": "[concat(parameters('settingsObject')[copyIndex('WVDhostpoolCopy')].workspaceName, '-Workspace')]",
Workspace needs to be named like this to match the Microsoft linked template.

2020-07-26 12:41 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                            "name": "[concat(parameters('settingsObject')[copyIndex('WVDhostpoolCopy')].hostpool.hostpoolName, '-DAG')]",
Desktop Application Group (DAG) needs to be named like this to match the Microsoft linked template.

2020-07-26 12:42 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                "name": "rgCopy",
Corrected.

2020-07-26 12:46 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +            "dependsOn": ["[resourceId('Microsoft.Resources/resourceGroups', parameters('settingsObject')[copyIndex('WVDhostpoolCopy')].rgName)]"],
Not that I can see, 'dependsOn' is an Array of items, there just happens to be one.

2020-07-26 12:47 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-settingsObject $SettingsObject
Corrected.

2020-07-26 12:49 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Name "New-CmAzWVD_$(Get-Date -Format 'ddMMyyHHmmss')" `
This is the name of the Azure deployment.

2020-07-26 12:53 UTC, tmshaunporter commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +- workspaceName: wvdjames
Unsure about this.

2020-07-26 12:54 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				[array]$SettingsObject = Get-CmAzSettingsFile -Path $SettingsFile
Unsure about this, the [array] usage was just stopping problems when the yml file had 1 item.

2020-07-26 12:56 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +		foreach ($Workspace in $SettingsObject.Clone()) {
.Clone() works for what is being done, anything that is set on $Workspace in the loop is also set in $SettingsObject - makes it easier to pass $SettingsObject into the ARM template.

2020-07-26 12:58 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-TemplateFile "C:\Source\cloudmarque-azure-pwsh\Cloudmarque.Azure\Public\IaaS\wvd\New-CmAzWVDHostpools.json" `
Done, this was just for testing.

2020-07-26 12:58 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-TemplateFile "C:\Source\cloudmarque-azure-pwsh\Cloudmarque.Azure\Public\IaaS\wvd\New-CmAzWVDHosts.json" `
Done, this was just for testing.

2020-07-26 13:00 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +		Remove-Variable Workspace
remove-variable is used because I use the same name in the next loop and prefer to 'tidy up'.

2020-07-26 13:01 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			New-AzWvdRegistrationInfo -ResourceGroupName $Workspace.rgName -HostPoolName $Workspace.hostpool.hostpoolName -ExpirationTime ((Get-Date).AddDays('1'))
Honestly unsure, probably need to speak to James about what lengths they used for the token - I'm not really sure why it has an expiry at all.

2020-07-26 13:22 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$Workspace.rgName = $wvdResourceGroupName
Corrected, I think...

2020-07-26 13:23 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$NetworkDetails = Get-AzResource -Name $Workspace.hostpool.hostVmVnet -ResourceType "Microsoft.Network/virtualNetworks" | Where-Object {$_.Location -EQ $Workspace.hostpool.hostVmLocation.Replace("
Need to know how it works for network details etc and try replicating it.

2020-07-26 13:28 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$LatestImage = Get-AzVMImageSku -Location $Workspace.hostpool.hostVmLocation -PublisherName "MicrosoftWindowsDesktop" -Offer $Workspace.hostpool.hostVmImage | Where-Object {$_.Skus -like "*-evd" -
Good point, added an IF statement.

2020-07-26 13:30 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				# }
Removed now.

2020-07-26 13:31 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$Workspace.hostpool.deploymentId = Get-Date -Format "ddMMyy-HHmmss"
The deploymentId thing is in the Microsoft linked template, I'm not actually sure its needed though and will need to test removing.

2020-07-26 13:31 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				$Workspace.hostpool.hostVmInitialNumber = 0
Changed.

2020-07-26 13:31 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				$Workspace.hostpool.hostVmInitialNumber = 0
Changed.

2020-07-26 13:33 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				Get-AzVM -ResourceGroupName $Workspace.rgName -Status | Where-Object PowerState -NotLike "VM running" | Start-AzVM
Starting the VM's are for if the deployment is going over an old deployment, VM's being stopped causes problems.

2020-07-26 13:38 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Location $SettingsObject[0].workspaceLocation `
This is a weird one of New-AzDeployment, the deployment is to the subscription but the cmdlet requires a location - even though it's not really useful so I just set it to jump though the hoop.

2020-07-26 13:38 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Location $SettingsObject[0].workspaceLocation `
This is a weird one of New-AzDeployment, the deployment is to the subscription but the cmdlet requires a location - even though it's not really useful so I just set it to jump though the hoop.

2020-07-26 13:41 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +        "settingsObject": {
Changed I believe...

2020-07-26 14:08 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                                "platformUpdateDomainCount": 5
Possibly, likely a discussion with James etc or suggestions how to deal with it - I'm trying to avoid configurable aspects just for the sake of configuration.

2020-07-26 14:09 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                                "name": "Aligned"
Not really no, it depends on the HDD selected, which at the moment is just 'managed' disks;
"Use 'Aligned' for virtual machines with managed disks and 'Classic' for virtual machines with unmanaged disks. Default value is 'Classic'."

2020-07-26 14:09 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHosts.json
> +            "type": "Array"
Changed.

2020-07-26 14:10 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHosts.json
> +                    "uri": "https://catalogartifact.azureedge.net/publicartifacts/Microsoft.Hostpool-ARM-1.0.13-preview/managedDisks-galleryvm.json",
This depends on the managed/unmanaged disk thing again - at the moment I'm only using managed.

2020-07-27 08:53 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +- workspaceName: wvdjames
Basically store everything under $Settings.Workspaces instead of directly iterating over the $Settings, which means you don't need to cast the object and also makes it clear what you are iterating over.

2020-07-27 08:54 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				[array]$SettingsObject = Get-CmAzSettingsFile -Path $SettingsFile
Storing the workspaces array under the workspaces property should resolve this issue.

2020-07-27 11:01 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +		foreach ($Workspace in $SettingsObject.Clone()) {
Removed and resolved now, works without.

2020-07-27 11:02 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Name "New-CmAzWVD_$(Get-Date -Format 'ddMMyyHHmmss')" `
Removed and resolved now, works without.

2020-07-27 11:02 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			New-AzWvdRegistrationInfo -ResourceGroupName $Workspace.rgName -HostPoolName $Workspace.hostpool.hostpoolName -ExpirationTime ((Get-Date).AddDays('1'))
Removed and resolved now, works without.

2020-07-27 11:02 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Name "New-CmAzWVD_$(Get-Date -Format 'ddMMyyHHmmss')" `
Removed and resolved now, works without.

2020-07-27 11:10 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostpoolFriendlyName: Windows Virtual Desktop
I think you can scrap three instances of name from the config. Just use one name setting only (contextual) ..run it through resource generator or powershell script to generate workspace name, friendly name(if required), and hostnpoolname. May be you can also include vmNamePrefix in that.

2020-07-27 11:11 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostVmSubnet: default
Default common settings and make them all optional. May reduce size of settings file.. You can refer to web.yml

2020-07-27 11:18 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +		Remove-Variable Workspace
Gone.

2020-07-27 14:45 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$NetworkDetails = Get-AzResource -Name $Workspace.hostpool.hostVmVnet -ResourceType "Microsoft.Network/virtualNetworks" | Where-Object {$_.Location -EQ $Workspace.hostpool.hostVmLocation.Replace("
Ok, but final implementation will need to use the service locator

2020-07-27 17:17 UTC, tmshaunporter commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostpoolFriendlyName: Windows Virtual Desktop
'Workspace' and 'host pool' are not the same thing and 'friendly names' are as they sound - they show to the end user in the log on portal so cannot be generated.

2020-07-27 17:17 UTC, tmshaunporter commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostVmSubnet: default
Not sure what is meant by this?

2020-07-27 17:17 UTC, tmshaunporter commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +- workspaceName: wvdjames
Suggested changes made, resolving.

2020-07-27 17:17 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				[array]$SettingsObject = Get-CmAzSettingsFile -Path $SettingsFile
Suggested changes made, resolving.

2020-07-27 17:18 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Location $SettingsObject[0].workspaceLocation `
Changed -Location to "UK South", as this is just where the deployment info is stored in Azure and not where the deployment itself takes place, resolving.

2020-07-27 17:18 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Location $SettingsObject[0].workspaceLocation `
Changed -Location to "UK South", as this is just where the deployment info is stored in Azure and not where the deployment itself takes place, resolving.

2020-07-27 17:21 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +
Implemented, resolving.

2020-07-27 17:40 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$NetworkDetails = Get-AzResource -Name $Workspace.hostpool.hostVmVnet -ResourceType "Microsoft.Network/virtualNetworks" | Where-Object {$_.Location -EQ $Workspace.hostpool.hostVmLocation.Replace("
Completed, resolving.

2020-07-27 18:09 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostpoolFriendlyName: Windows Virtual Desktop
While i agree with you Shaun on the friendly names, one name property in settings should be used for all other generated resource names. This is because the name property is designed to provide contextual info for all resources being deployed, for example with our static website cmdlet, the name is usually set to what the website is designed for.

2020-07-28 14:00 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +
Key Vault implementation completed, resolving.

2020-07-28 14:21 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                            "name": "[concat(parameters('settingsObject')[copyIndex('WVDhostpoolCopy')].hostpool.hostpoolName, '-DAG')]",
May have to correct myself here, have been through the process from start to finish and it looks like only "*-availabilitySet-*" is needed to be coded strictly for being passed into the linked template.

2020-07-28 14:21 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                            "name": "[concat(parameters('settingsObject')[copyIndex('WVDhostpoolCopy')].workspaceName, '-Workspace')]",
May have to correct myself here, have been through the process from start to finish and it looks like only "*-availabilitySet-*" is needed to be coded strictly for being passed into the linked template.

2020-07-29 09:00 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                                // Sku of the availability set, only name is required to be set. See AvailabilitySetSkuTypes for possible set of values. Use 'Aligned' for virtual machines with manage
Move comment above the name property

2020-07-29 09:01 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHosts.json
> +                "name": "WVDhostsCopy",
Capital H

2020-07-29 13:36 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +	 	 New-CmAzWVD -SettingsObject $settings
Completed

2020-07-29 13:36 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$WvdResourceGroupName = Get-CmAzResourceName -Resource "ResourceGroup" -Architecture "IaaS" -Region $Workspace.workspaceLocation -Name $Workspace.workspaceName
Done

2020-07-29 13:36 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$Workspace.rgName = $WvdResourceGroupName
Done

2020-07-29 13:36 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +		foreach ($Workspace in $SettingsObject.wvdEnvironments) {
Done

2020-07-29 13:36 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +		foreach ($Workspace in $SettingsObject.wvdEnvironments) {
Done

2020-07-29 13:37 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$NetworkDetails = Get-CmAzService -Service $Workspace.hostpool.hostVmVnet -Region $Workspace.hostpool.hostVmLocation
Done

2020-07-29 13:37 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$LatestImage = Get-AzVMImageSku -Location $Workspace.hostpool.hostVmLocation -PublisherName "MicrosoftWindowsDesktop" -Offer $Workspace.hostpool.hostVmImage | Where-Object {$_.Skus -like "*-evd" -
Done

2020-07-29 13:37 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			}
Done

2020-07-29 13:37 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$CurrectVMList = Get-AzResource -ResourceGroupName $Workspace.rgName -ResourceType "Microsoft.Compute/virtualMachines"
Done

2020-07-29 13:37 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			}
Done

2020-07-29 13:38 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                                // Sku of the availability set, only name is required to be set. See AvailabilitySetSkuTypes for possible set of values. Use 'Aligned' for virtual machines with manage
Done

2020-07-29 13:38 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHosts.json
> +                "name": "WVDhostsCopy",
Done

2020-07-29 13:38 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				Write-Error "Cannot find key encryption key in Key Vault." -Category InvalidArgument -CategoryTargetName "hostVmKeyVaultAdminSecret"
I think this is done? Not entirely sure what is meant

2020-07-29 13:41 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$keyVaultSecret = $keyVault | Get-AzKeyVaultSecret -Name $Workspace.hostpool.hostVmKeyVaultAdminSecret
Nope, complete secret I believe.

2020-07-30 08:59 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostVmSubnet: default
Did you two resolve this issue?

2020-08-05 07:23 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			New-AzWvdRegistrationInfo -ResourceGroupName $Workspace.rgName -HostPoolName $Workspace.hostpool.hostpoolName -ExpirationTime ((Get-Date).AddDays('1'))
Spoken with James, he agrees with me - expiration being set as is would be fine, as this is just used for an initial connection to the hostpool from the host vms.

2020-08-05 07:24 UTC, tmshaunporter commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostVmSubnet: default
Changes made, resolving.

2020-08-10 07:19 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                            "name": "[concat(parameters('settingsObject')[copyIndex('WVDhostpoolCopy')].workspaceName, '-Workspace')]",
Fixed, resolving.

2020-08-10 07:19 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHostpools.json
> +                            "name": "[concat(parameters('settingsObject')[copyIndex('WVDhostpoolCopy')].hostpool.hostpoolName, '-DAG')]",
Fixed, resolving.

2020-08-20 11:21 UTC, tm-luke requested changes

2020-08-20 11:21 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +- wvdEnvironmentName: cmaz-auto # Used to generate the names of the Azure resources.
Tab out these comments, and align them on the right

2020-08-20 11:21 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			# "core.logging.loganalytics"
Remove above comment

2020-08-20 11:21 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			Write-Verbose "Generated resource group name: $($wvdEnvironment.resourceGroupName)"
Newline above

2020-08-20 11:21 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			Write-Verbose "Generated Workspace name: $($wvdEnvironment.workspaceName)"
Newline above

2020-08-20 11:21 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			Write-Verbose "Generated Hostpool name: $($wvdEnvironment.hostpool.hostpoolName)"
Newline above

2020-08-20 11:21 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			Write-Verbose "Generated Desktop Application Group name: $($wvdEnvironment.desktopGroupName)"
Newline above

2020-08-20 11:21 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			$wvdEnvironment.hostVm.vmTemplateString = ($vmTemplateString | ConvertTo-Json).Replace("`r`n","") -Replace (' +',"")
Newline above

2020-08-20 11:21 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			if ($null -eq $keyVault) {
Newline above

2020-08-20 11:21 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			if ($null -eq $keyVaultSecret) {
Newline above

2020-08-20 11:21 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +		Write-Verbose "Deploying WVD hosts."
Newline above

2020-08-20 11:21 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +		Write-Verbose "Deploying WVD host post setup."
Newline above

2020-08-21 07:26 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				}
Yes it is, try it :)

2020-08-21 07:28 UTC, tmshaunporter commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +- wvdEnvironmentName: cmaz-auto # Used to generate the names of the Azure resources.
Fixed

2020-08-21 08:47 UTC, deepend-dev requested changes

2020-08-21 08:47 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-SettingsObject $SettingsObject.wvdEnvironments
can we not combine both the deployments with 2 "deployment resource" and depends on in a single template.

2020-08-21 08:47 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDEnvironment.json
> +            "enabled": true,
guess we should be defaulting this but allow customer to change it.. critical option in terms of monitoring.

2020-08-21 08:47 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostpoolFriendlyName: cmaz-auto                                   # Used to display the friendly name to the user on the login portal.
can we use same friendly name for hostpool and workspace

2020-08-21 08:47 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostpoolMaxSessions: 5                                            # The number of users allowed on a 'pooled' resource.
you can default above three value for pooled as that would be most used scenario, and have these parameters as optional..

2020-08-21 08:47 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostVmSize: Standard_DS1_v2                                       # Standard Azure virtual machine sizes.
Do you think wvd environment location can differ from hostVM location .. If yes, can we default this to wvd location. if not remove hostvmlocation completely

2020-08-21 08:47 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +  logAnalyticsLinkName: cmaz-wide link to LA
may be we can pull out log analytics to root level of file. I dont think it will be environment specific.

2020-08-26 07:25 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			#$latestImage = Get-AzVMImageSku -Location $wvdEnvironment.hostVm.hostVmLocation -PublisherName "MicrosoftWindowsDesktop" -Offer $wvdEnvironment.hostVm.hostVmImage | Where-Object {$_.Skus -like "*
In my mind, at the moment - yes, it was coded to use the latest image available on the gallery (2004) but that doesn't work and shows the hosts as 'unavailable', so 1904 is forced for the time being.

2020-08-26 07:25 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				Write-Error "No valid images returned from Azure Gallery." -Category InvalidArgument -CategoryTargetName "Gallery image"
It probably would but I hate that coding practice, find it too difficult to read.

2020-08-26 07:27 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Location "Uk South" `
This is just for the subscription level deployment and where its deployment logs are stored, if you have a better idea I'm all ears? but it doesn't seem to matter much

2020-08-26 07:28 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDEnvironment.json
> +            "enabled": true,
I just copied Luke's to be honest, @tm-luke thoughts?

2020-08-26 07:30 UTC, tmshaunporter commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostpoolFriendlyName: cmaz-auto                                   # Used to display the friendly name to the user on the login portal.
It's certainly possible but I don't feel it would make much sense on how it displays in the portal, you'd have the same friendly name showing twice.

2020-08-26 07:31 UTC, tmshaunporter commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostpoolMaxSessions: 5                                            # The number of users allowed on a 'pooled' resource.
Not sure what this means?

2020-08-26 07:32 UTC, tmshaunporter commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +  logAnalyticsLinkName: cmaz-wide link to LA
I don't think that's something I can fix, haha - @tm-luke ?

2020-08-26 07:33 UTC, tmshaunporter commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostVmSize: Standard_DS1_v2                                       # Standard Azure virtual machine sizes.
wvd environments are only in America at the moment, but their host vms can be elsewhere (if thats what you're asking, I don't fully understand?)

2020-08-26 07:36 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-SettingsObject $SettingsObject.wvdEnvironments
I aimed for it to be in a single template originally, but the hostpool registration key can only be made after the host pool is made via a powershell cmdlet, from what I could figure out.  unless something has changed or there was something I missed, I had to split them into 2.

2020-08-26 08:44 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Location "Uk South" `
may be default to location of resourcegroup

2020-08-27 09:50 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Location "Uk South" `
I recommend making the location a configurable setting, but without a default value as i want the location choice to be conscious decision for the user.

2020-08-27 09:55 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				Write-Error "No valid images returned from Azure Gallery." -Category InvalidArgument -CategoryTargetName "Gallery image"
Change to !$latestImage for consistency with the rest of the codebase.

2020-08-27 10:02 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDEnvironment.json
> +            "enabled": true,
We have an active issue to ensure that log analytics is a configurable setting across all resources, instead of enforcing all resources to reference an existing log analytics resource. With that in mind, i am fine with the setting being omitted if the value is defaulted to false.

2020-08-27 10:03 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostpoolMaxSessions: 5                                            # The number of users allowed on a 'pooled' resource.
Has there been any headway with this?

2020-08-27 10:05 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostVmSize: Standard_DS1_v2                                       # Standard Azure virtual machine sizes.
From what i understand, we can default the hostVMLocation to the WVDEnvironment location if that setting isn't populated, which makes sense.

2020-08-27 10:06 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +  logAnalyticsLinkName: cmaz-wide link to LA
I would move the logAnalyticsTag to be a root level setting (top of the file) that applies to all applicable resources that are being deployed, instead of on a per environment basis.

2020-08-27 10:50 UTC, tm-luke requested changes

2020-08-27 10:50 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				{$_ -like "gallery"} {
Using -like in this way is asserting that $_ is equal to "gallery", if this is intentional i'd rather you swap the operator to      -eq instead.

2020-08-27 10:50 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +					$latestImage = (Get-AzVMImageSku -Location $wvdEnvironment.hostVm.hostVmLocation -PublisherName "MicrosoftWindowsDesktop" -Offer $wvdEnvironment.hostVm.hostVmImage | Where-Object {$_.Skus -like
Using -like in this way is asserting that $_ is equal to "19h2-evd", if this is intentional i'd rather you swap the operator to      -eq instead

2020-08-27 10:50 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				{$_ -like "customimage"} {
Using -like in this way is asserting that $_ is equal to "customimage", if this is intentional i'd rather you swap the operator to -eq instead.

2020-08-27 10:50 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +function New-CmAzWVD {
Need to add Iaas to the cmd name

2020-08-28 08:04 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +			-Location "Uk South" `
Complete.

2020-08-28 08:05 UTC, tmshaunporter commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostpoolMaxSessions: 5                                            # The number of users allowed on a 'pooled' resource.
Yes. added more defaulting.

2020-08-28 08:05 UTC, tmshaunporter commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +    hostVmSize: Standard_DS1_v2                                       # Standard Azure virtual machine sizes.
Complete.

2020-08-28 08:06 UTC, tmshaunporter commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +  logAnalyticsLinkName: cmaz-wide link to LA
Done.

2020-08-28 08:06 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				{$_ -like "gallery"} {
Changes made.

2020-08-28 08:06 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +					$latestImage = (Get-AzVMImageSku -Location $wvdEnvironment.hostVm.hostVmLocation -PublisherName "MicrosoftWindowsDesktop" -Offer $wvdEnvironment.hostVm.hostVmImage | Where-Object {$_.Skus -like
Changes made.

2020-08-28 08:06 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +				{$_ -like "customimage"} {
Changes made.

2020-08-28 08:06 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVD.ps1
> +function New-CmAzWVD {
Changes made.

2020-09-02 11:20 UTC, deepend-dev requested changes
few minor changes

2020-09-02 11:20 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzIaaSWVD.ps1
> +				$wvdEnvironment.hostVm.hostVmLocation = $wvdEnvironment.wvdEnvironmentLocation
can we use !$wvdEnvironment.hostVm.hostVmLocation instead of -eq $null?

2020-09-02 11:20 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzIaaSWVD.ps1
> +				$wvdEnvironment.logAnalyticsLinkName = "WVD Log Analytics Link"
you might need to default id and name or they can issue with arm template

2020-09-02 11:20 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzIaaSWVD.ps1
> +					"ram" = (Get-AzVMSize -Location $($wvdEnvironment.hostvm.hostVmLocation).Replace(" ","") | Where-Object {$_.name -eq $wvdEnvironment.hostvm.hostVmSize}).MemoryInMB / 1Gb
rather then making two api calls using get-azvmsize, can we find way to do just a single call for same component? will improve performance of script

2020-09-02 11:20 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzIaaSWVD.ps1
> +			$SettingsObject.azureDeploymentLocation = "UK South"
rather then defaulting to UK south, i would suggest to default location to wvd[0] location

2020-09-02 11:20 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzIaaSWVD.ps1
> +			IF ($null -ne $CurrentVMList) {
IF ==> if

2020-09-02 11:20 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +logAnalyticsTag: log.analyticsnew                                      # Uses Cloudmarque service locator.
this should be optional as well

2020-09-02 11:31 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzIaaSWVD.ps1
> +					"ram" = (Get-AzVMSize -Location $($wvdEnvironment.hostvm.hostVmLocation).Replace(" ","") | Where-Object {$_.name -eq $wvdEnvironment.hostvm.hostVmSize}).MemoryInMB / 1Gb
yeah you're right, RAM wasn't in the first iteration and the current version was just a copy/paste of something which worked.

2020-09-02 11:32 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzIaaSWVD.ps1
> +				$wvdEnvironment.hostVm.hostVmLocation = $wvdEnvironment.wvdEnvironmentLocation
You can, I never will though :) as I mentioned previously I find it stupidly difficult to read and never code like that personally.

2020-09-02 11:44 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzIaaSWVD.ps1
> +				$wvdEnvironment.logAnalyticsLinkName = "WVD Log Analytics Link"
no, I think its accounted for in the same manner in the arm templates, if the tag is null it doesn't deploy.

2020-09-02 11:45 UTC, tmshaunporter commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzIaaSWVD.ps1
> +			$SettingsObject.azureDeploymentLocation = "UK South"
I had this previously but changed it as per @tm-luke request.

2020-09-02 12:58 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzIaaSWVD.ps1
> +					"ram" = (Get-AzVMSize -Location $($wvdEnvironment.hostvm.hostVmLocation).Replace(" ","") | Where-Object {$_.name -eq $wvdEnvironment.hostvm.hostVmSize}).MemoryInMB / 1Gb
Yeah try and save on cmdlet call where you can

2020-09-02 13:01 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzIaaSWVD.ps1
> +			$SettingsObject.azureDeploymentLocation = "UK South"
Yeah this suggestion doesn't quite make sense, if we deploy vms to multiple locations. Is there another resource we can set this to match instead?

2020-09-02 13:06 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzIaaSWVD.ps1
> +			IF ($null -ne $CurrentVMList) {
Yeah this needs changing

2020-09-02 13:06 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +logAnalyticsTag: log.analyticsnew                                      # Uses Cloudmarque service locator.
This is optional as far as im aware

2020-09-02 13:07 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzIaaSWVD.ps1
> +				$wvdEnvironment.logAnalyticsLinkName = "WVD Log Analytics Link"
This definitely needs defaulting, have encountered this issue on further testing.

2020-09-02 14:17 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzIaaSWVD.ps1
> +			$SettingsObject.azureDeploymentLocation = "UK South"
if we deploy vm to multiple location, as default we should be picked up a location (probably first one) from of the locations rather then defaulting to UK south which might not be necessary be deployed at... At least with former we are sure that location is in use

2020-09-02 14:20 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/wvd.yml
> +logAnalyticsTag: log.analyticsnew                                      # Uses Cloudmarque service locator.
in that case, need to be mentioned in yml file.

2020-09-08 09:13 UTC, tm-luke approved these changes

2020-09-08 10:07 UTC, merged