Common - Set-CmAzContext - resolves issue with existing folder missing required files
Trustmarque/cloudmarque-azure-pwsh pull request #74
Opened 2020-09-04 11:26 UTC by deepend-dev

resolves #73

2020-09-04 18:54 UTC, tm-luke requested changes

2020-09-04 18:54 UTC, tm-luke commented on Tests/Test-CmAzContext.Tests.ps1
> +
No need for extra line

2020-09-04 18:54 UTC, tm-luke commented on Tests/Test-CmAzContext.Tests.ps1
> +			$actualItems = Get-ChildItem "$testProjectRoot/_names" -Recurse -Force
I know _names is the only "required" directory for Cloudmarque to work, but this tests that new-cmazproject copies all settings files and everything in _names to a new directory. Checking that _names exists is a valid way to check if a project has been created in a specified directory, but i would rather check that everything gets copied for this test.

2020-09-04 18:54 UTC, tm-luke commented on Tests/Test-CmAzContext.Tests.ps1
> +		$azureContextFilePath = "$PSScriptRoot/context.json"
Good catch

2020-09-04 18:54 UTC, tm-luke commented on Tests/New-CmAzProject.Tests.ps1
> +			$destinationItems = Get-ChildItem "$destination\_names" -Recurse -Force
See below, also looks like we might be testing the same thing twice?

2020-09-04 18:54 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/New-CmAzProject.ps1
> +		New-Item -Path "$Project/Readme.md" -ItemType File -Value "# Settings Files for CloudMarque.Azure`n" -force | Out-Null
'> $null' is the same isn't it?

2020-09-04 18:54 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/New-CmAzProject.ps1
> +		New-Item -Path "$Project/Readme.md" -ItemType File -Value "# Settings Files for CloudMarque.Azure`n" -force | Out-Null
-Force instead of -force

2020-09-04 18:54 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/New-CmAzProject.ps1
> +		New-Item -Path "$Project/Readme.md" -ItemType File -Value "# Settings Files for CloudMarque.Azure`n" -force | Out-Null
Same with -filter

2020-09-04 18:54 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/New-CmAzProject.ps1
> +		$Source = "$PSScriptRoot/../../Resources/Project/_names"
Might need to discuss this further, we still want the settings files to be copied i would have thought

2020-09-04 18:54 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +				}
I would flag all the missing files instead of stopping at each one.

2020-09-04 18:54 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +				$ProjectConfirmation = Read-Host -Prompt "Project folder doesn't have all required files vital for cloudmarque operations.`nDo you want us to create new project root with necessary files? This wi
Capitalize Cloudmarque.

2020-09-04 18:54 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +				$ProjectConfirmation = Read-Host -Prompt "Project folder doesn't have all required files vital for cloudmarque operations.`nDo you want us to create new project root with necessary files? This wi
Change "Do you want us to create new project root with necessary files? This will overwrite existing files" 
to this  "Do you want to create a new project? This will overwrite existing files."

2020-09-04 18:54 UTC, tm-luke commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +					throw "`nProject folder is missing name generation files vital for cloudmarque operations.`nEither generate a new project or upload _names directory from cloudmarque to target folder."
Change error message to this:  "Project is missing files required for Cloudmarque operations, either create a new project or restore the missing files."

2020-09-07 07:59 UTC, deepend-dev commented on Tests/Test-CmAzContext.Tests.ps1
> +			$actualItems = Get-ChildItem "$testProjectRoot/_names" -Recurse -Force
This actually checks all files in _names are present or not, not just the folder

PS /home/vsonline/workspace/cloudmarqzure-pwsh> Get-ChildItem ./projectroot/_names/ -Recurse



    Directory: /home/vsonline/workspace/cloudmarque-azu
re-pwsh/projectroot/_names

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-----          07/02/2020    12:49           2466 gener
                                                  ators
                                                  .yml
-----          07/19/2020    13:26            329 regio
                                                  ns.ym
                                                  l
-----          07/02/2020    12:49           8616 resou
                                                  rces.
                                                  yml
-----          07/02/2020    12:49            245 token
                                                  s.yml
-----          07/08/2020    16:20           2284 web.y
                                                  ml

PS /home/vsonline/workspace/cloudmarque-azure-pwsh>

2020-09-07 08:00 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +				}
done

2020-09-07 08:01 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +				}
it breaks the loop at first missing file and straight away requests to create new project

2020-09-07 08:01 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +				$ProjectConfirmation = Read-Host -Prompt "Project folder doesn't have all required files vital for cloudmarque operations.`nDo you want us to create new project root with necessary files? This wi
done

2020-09-07 08:04 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
> +					throw "`nProject folder is missing name generation files vital for cloudmarque operations.`nEither generate a new project or upload _names directory from cloudmarque to target folder."
done

2020-09-07 08:07 UTC, deepend-dev commented on Tests/New-CmAzProject.Tests.ps1
> +			$destinationItems = Get-ChildItem "$destination\_names" -Recurse -Force
one is for new project command and another is for context when projectconfirmation is yes

2020-09-07 08:07 UTC, deepend-dev commented on Tests/Test-CmAzContext.Tests.ps1
> +
done

2020-09-07 10:44 UTC, tm-luke commented on Tests/Test-CmAzContext.Tests.ps1
> +			$actualItems = Get-ChildItem "$testProjectRoot/_names" -Recurse -Force
Yes but what i'm saying is i want this test to check that all settings files are copied as well.

2021-01-18 12:32 UTC, tm-luke commented
Not applicable anymore, closing..

2021-01-18 12:32 UTC, closed without merging