Paas - New-CmAzPaasSharedImageGallery initial draft
Trustmarque/cloudmarque-azure-pwsh pull request #81
Opened 2020-09-11 04:05 UTC by deepend-dev

2020-09-14 14:17 UTC, tm-luke requested changes

2020-09-14 14:17 UTC, tm-luke commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzpaasSharedImageGallery.json
> +                "count": "[length(parameters('SIGObjectArray'))]"
Can we simplify this name? If its a list of shared image galleries then SharedImageGalleryCopy is fine.

2020-09-14 14:17 UTC, tm-luke commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzpaasSharedImageGallery.json
> +                },
Can we use outer here? Means less parameter copying

2020-09-14 14:17 UTC, tm-luke commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzpaasSharedImageGallery.ps1
> +                    Write-Verbose
Unsure about this

2020-09-14 14:17 UTC, tm-luke commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzpaasSharedImageGallery.ps1
> +                    $_.endOfLifeDate = (([datetime]::Parse($_.endOfLifeDate)).GetDateTimeFormats('s')).Split()
Powershell-yaml handles datetimes, do we need the parsing here?

2020-09-14 14:17 UTC, tm-luke commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzpaasSharedImageGallery.ps1
> +                    $date = ((Get-date).AddYears('5').GetDateTimeFormats('s')).split()
Wondering if we can set this to the datetime maxvalue, not filling in a endOfLifeDate implies the user doesn't want it to expire.

2020-09-14 14:17 UTC, tm-luke commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzpaasSharedImageGallery.ps1
> +                if (!$_.osType) {
Maybe set the variable, then add it to the verbose string, apply the same to any similar instances below.

2020-09-14 14:17 UTC, tm-luke commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzpaasSharedImageGallery.ps1
> +                    -SIGObjectArray $SettingsObject.imageDefinations `
imageDefinitions

2020-09-14 14:17 UTC, tm-luke commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/sharedImageGallery.yml
> +    publisher: "string"
Tab out any comments in settings.

2020-09-14 15:25 UTC, deepend-dev commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzpaasSharedImageGallery.json
> +                },
there are multiple levels of inner loops which wont work

2020-09-14 15:25 UTC, deepend-dev commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzpaasSharedImageGallery.json
> +                "count": "[length(parameters('SIGObjectArray'))]"
done

2020-09-14 15:25 UTC, deepend-dev commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzpaasSharedImageGallery.ps1
> +                    Write-Verbose
thanks for catching this. corrected

2020-09-14 15:26 UTC, deepend-dev commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzpaasSharedImageGallery.ps1
> +                    $date = ((Get-date).AddYears('5').GetDateTimeFormats('s')).split()
ideally they should. as there will be security fix and vulnerability fixes..

2020-09-14 15:28 UTC, deepend-dev commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzpaasSharedImageGallery.ps1
> +                if (!$_.osType) {
didnt get this

2020-09-14 15:28 UTC, deepend-dev commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzpaasSharedImageGallery.ps1
> +                    -SIGObjectArray $SettingsObject.imageDefinations `
done

2020-09-14 15:28 UTC, deepend-dev commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/sharedImageGallery.yml
> +    publisher: "string"
done

2020-09-15 08:36 UTC, tm-luke requested changes

2020-09-15 08:36 UTC, tm-luke commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzPaasSharedImageGallery.ps1
> +                    Write-Verbose "Default: image defination location will be defaulted Shared imaged gallery : $($SettingsObject.location)"
definition not defination

2020-09-15 08:36 UTC, tm-luke commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzPaasSharedImageGallery.ps1
> +                    Write-Verbose "Default: image defination location will be defaulted Shared imaged gallery : $($SettingsObject.location)"
There seem to be multiple instances of this, can you change this in all files please

2020-09-15 08:36 UTC, tm-luke commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzPaasSharedImageGallery.ps1
> +                    $_.osType = "Linux"
What i mean is, maybe set the ostype, the use it in the string, theres a few places where this change can be applied.

2020-09-15 08:36 UTC, tm-luke commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzPaasSharedImageGallery.ps1
> +                    $date = ((Get-date).AddYears('5').GetDateTimeFormats('s')).split()
Good point, adding a few years is fine actually.

2020-09-15 08:58 UTC, deepend-dev commented on Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzPaasSharedImageGallery.ps1
> +                    Write-Verbose "Default: image defination location will be defaulted Shared imaged gallery : $($SettingsObject.location)"
yes 👍

2020-09-15 10:47 UTC, tm-luke submitted a review, later dismissed

2020-09-15 14:03 UTC, tm-luke approved these changes

2020-09-15 14:03 UTC, merged