Iaas - Storage account implementation
Trustmarque/cloudmarque-azure-pwsh pull request #95
Opened 2020-09-23 12:28 UTC by deepend-dev

2020-10-08 17:11 UTC, tm-luke requested changes
Need to amend this work to include the new tagging changes.

2020-10-09 15:59 UTC, tm-luke requested changes

2020-10-09 15:59 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/storage/New-CmAzIaasStorage.json
> +                            }
Amend to storage, so its in keeping with other cmdlets

2020-10-09 15:59 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/storage/New-CmAzIaasStorage.ps1
> +
Same as above

2020-10-09 15:59 UTC, tm-luke commented on Cloudmarque.Azure/Public/IaaS/storage/New-CmAzIaasStorage.ps1
> +		}
I would check if the resource group exists instead and use a if/else statement instead of trying to set tags on the resourcegroups by default

2020-10-09 15:59 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/storage.yml
>    - storageAccountName:
Provide an example of resource level tagging as well.

2020-10-09 16:07 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/storage/New-CmAzIaasStorage.json
> +                            }
Done

2020-10-09 16:08 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/storage/New-CmAzIaasStorage.ps1
> +		}
its being checked above

2020-10-09 16:08 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/storage.yml
>    - storageAccountName:
done

2020-10-09 16:08 UTC, deepend-dev commented on Cloudmarque.Azure/Public/IaaS/storage/New-CmAzIaasStorage.ps1
> +
done

2020-10-13 16:18 UTC, tm-luke requested changes

2020-10-13 16:18 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/storage.yml
> +    blobContainer:
Need examples of names and publicaccess here, you can highlight the public access property is optional here.

2020-10-13 16:18 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/storage.yml
> +      - blob1
Need examples of names and publicaccess here, you can highlight the public access property is optional here.

2020-10-13 16:18 UTC, tm-luke commented on Cloudmarque.Azure/Resources/Project/storage.yml
> +  - storageAccountName:                         # Exanple Static website on blob
M not n in Example, might be better to provide an actual storage account name

2020-10-14 10:56 UTC, deepend-dev commented on Cloudmarque.Azure/Public/Core/monitoring/New-CmAzCoreMonitor.ps1
> +					blobContainer = @(
updated

2020-10-14 10:57 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/storage.yml
> +    blobContainer:
done

2020-10-14 10:57 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/storage.yml
> +      - Test1
done

2020-10-14 10:57 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/storage.yml
> +      - blob1
done

2020-10-14 10:57 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/storage.yml
> +      - blob1
done

2020-10-14 10:57 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/storage.yml
> +    resourceGroup:                             # For deployment to exisiting resource Group
done

2020-10-14 10:58 UTC, deepend-dev commented on Cloudmarque.Azure/Resources/Project/storage.yml
> +  - storageAccountName:                         # Exanple Static website on blob
done

2020-10-14 11:08 UTC, tm-luke approved these changes

2020-10-14 11:08 UTC, merged